services:
  mysql:
    image: mysql:8.0
    container_name: mysql_nest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
  nestjs-app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    restart: always
    ports:
      - "8888:8888"
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/education_db
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run seed && npm run start"
volumes:
  mysql_data:
